name: video2mvb

options:
  bundleIdPrefix: com.onee__chan

settings:
  configs:
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      GCC_OPTIMIZATION_LEVEL: 'fast'

targets:
  video2mvb:
    type: tool
    platform: macOS
    deploymentTarget: "11.0"
    sources:
      - path: ./Sources
    dependencies:
      - package: ArgumentParser

packages:
  ArgumentParser:
    url: https://github.com/apple/swift-argument-parser
    version: '1.2.0'
